FORMAT: 1A
HOST: http://sweet-travels.appspot.com

# kbruton18

SWEet Travels is an API that allows clients to query information from the SWEet Travels website.

## Parks Collection [/api/parks]
### List National Parks [GET]

List all national parks contained in SWEet Travels.

+ Response 200 (application/json)

        [
            {
                "campgrounds": "None",
                "description": "Did you know that Petrified Forest is more spectacular than ever? While the park has all the wonders known for a century, there are many new adventures and discoveries to share. There are backcountry hikes into areas never open before such as Red Basin and little known areas like the Martha's Butte. There are new exhibits that bring the stories to life. Come rediscover Petrified Forest!",
                "designation": "National Park",
                "directionsInfo": "Petrified Forest stretches north and south between I-40 and Highway 180. Westbound I-40 travelers should take Exit 311, drive the 28 miles through the park and connect with Hwy 180 at the south end. Travel 19 miles on Hwy 180 North to return to Interstate 40 via Holbrook. Eastbound I-40 travelers should take Exit 285 into Holbrook then travel 19 miles on Hwy 180 South to the park's south entrance. Drive the 28 miles north through the park to return to I-40.",
                "directionsUrl": "http://www.nps.gov/pefo/planyourvisit/directions.htm",
                "fullName": "Petrified Forest National Park",
                "imageUrl": "https://www.nps.gov/common/uploads/structured_data/3C7D8213-1DD8-B71B-0BE4A3B9394FD89A.jpg",
                "latLong": "lat:34.98387664, long:-109.7877678",
                "model": "park",
                "parkCode": "pefo",
                "searchString": "",
                "states": "AZ",
                "url": "https://www.nps.gov/pefo/index.htm",
                "weatherInfo": "Petrified Forest National Park is a semi-arid grassland. Temperatures range from above 100° F (38° C) to well below freezing. About 10 inches (25.4 cm) of moisture comes during infrequent snow in the winter and often violent summer thunder-storms. Animals and plants are adapted to extremes in temperature and moisture. You should be ready too. Check out the forecast before you arrive and plan accordingly."
            },
            {
                "campgrounds": "None",
                "description": "When Hansen's disease (leprosy) was introduced to the Hawaiian Islands, King Kamehameha V banished all afflicted to the isolated Kalaupapa peninsula on the north shore of Molokai.  \n\nSince 1866, more than 8000 people, mostly Hawaiians, have died at Kalaupapa. Once a prison, Kalaupapa is now refuge for the few remaining residents who are now cured, but were forced to live their lives in isolation.",
                "designation": "National Historical Park",
                "directionsInfo": "Kalaupapa is an extremely isolated place, surrounded on three sides by ocean and two-thousand foot cliffs on the fourth. Consequently, there is no road access into the peninsula. Kalaupapa cannot be reached by automobile. To get to the park, visitors must travel by air, mule, or on foot. See the park's Direction and Transportation webpage for additional information.",
                "directionsUrl": "http://www.nps.gov/kala/planyourvisit/directions.htm",
                "fullName": "Kalaupapa National Historical Park",
                "imageUrl": "https://www.nps.gov/common/uploads/structured_data/3C79B6CD-1DD8-B71B-0BB2B4265DD8C023.jpg",
                "latLong": "lat:21.1731108, long:-156.9511609",
                "model": "park",
                "parkCode": "kala",
                "searchString": "",
                "states": "HI",
                "url": "https://www.nps.gov/kala/index.htm",
                "weatherInfo": "Hawaii enjoys warm temperatures year-round, although site conditions at the park can vary depending on weather and time of year.  The rainy season is in the winter with the more hot and humid days in the summer. Trade winds are fairly constant and typically blow from the northeast. Daytime temperatures range from 65–75° F in the winter to 80-90°F in the summer. Nighttime temperatures are often in the 60-70°F range."
            },
            {
                ...
            }
        ]

## Visitor Centers Collection [/api/visitorcenters]
### List Visitor Centers [GET]

List all visitor centers contained in SWEet Travels.

+ Response 200 (application/json)

        [
            {
                "description": "Information, park movie, park passes, exhibits, and Eastern National bookstore.",
                "directionsInfo": "Located off ME 3 in Hulls Cove (just north of Bar Harbor) Hulls Cove Visitor Center is at the top of the hill above the large parking lots. An accessible entrance is also available.",
                "directionsUrl": "http://www.nps.gov/acad/planyourvisit/directions.htm",
                "imageUrl": "http://www.barharbormagic.com/images5/visitor-center-01.jpg",
                "latLong": "{lat:44.4084449, lng:-68.2459378}",
                "model": "visitorcenter",
                "name": "Hulls Cove Visitor Center",
                "parkCode": "acad",
                "searchString": "",
                "states": "ME",
                "website": "http://www.nps.gov/acad/planyourvisit/hours.htm"
            },
            {
                "description": "This center is located in the southeast corner of the park on State Route 123, 12 miles north of the town of Packwood. It is next to the Ohanapecosh Campground and near the trailhead for the Natural Hot Springs and Silver Falls. There are restrooms, exhibits, and a ranger or volunteer on duty to answer questions when it is open for the summer season.",
                "directionsInfo": "Ohanapecosh Visitor Center is on State Route 123, 12 miles north of the town of Packwood. It has no physical address. GPS users can enter 46.914466,-121.643404 for its location.",
                "directionsUrl": "http://www.nps.gov/mora/planyourvisit/directions.htm",
                "imageUrl": "https://2is1ib1gauzt43v0d61gfhsq-wpengine.netdna-ssl.com/wp-content/uploads/2014/07/0714_pal-760.jpg",
                "latLong": "{lat:46.73594152212533, lng:-121.565882563591}",
                "model": "visitorcenter",
                "name": "Ohanapecosh Visitor Center",
                "parkCode": "mora",
                "searchString": "",
                "states": "WA",
                "website": "http://www.nps.gov/mora/planyourvisit/ohanapecosh.htm"
            },
            {
                ...
            }
        ]



## State Collection [/api/states]

### List States [GET]

List all state objects contained in SWEet Travels.

+ Response 200 (application/json)

        [
            {
                "abbreviations": "WA",
                "campgrounds": "Cougar Rock,Mowich Lake,Ohanapecosh,White River",
                "capital": "Olympia, Washington",
                "governor": "Jay Inslee ",
                "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/5/54/Flag_of_Washington.svg",
                "largestCity": "Seattle",
                "medianIncome": "$67,243 ",
                "model": "state",
                "name": "Washington ",
                "nationalParks": "lewi,mapr,mora,sajh",
                "nicknames": "The Evergreen State",
                "searchString": "",
                "timeZone": "Pacific Time Zone",
                "totalArea": "71,362",
                "totalPopulation": "7,288,000 ",
                "url": "access.wa.gov"
            },
            {
                "abbreviations": "DE",
                "campgrounds": "",
                "capital": "Dover, Delaware",
                "governor": "John C. Carney Jr.",
                "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/c/c6/Flag_of_Delaware.svg",
                "largestCity": "Wilmington, Delaware",
                "medianIncome": "$57,756",
                "model": "state",
                "name": "Delaware",
                "nationalParks": "None",
                "nicknames": "The First State, The Small Wonder, Blue Hen State, The Diamond State",
                "searchString": "",
                "timeZone": "Eastern Time Zone ",
                "totalArea": "1,982",
                "totalPopulation": "952,065 ",
                "url": "http://delaware.gov/"
            }, 
            {
                ...
            }
        ]


## Campground Collection [/api/campgrounds]

### List Campgrounds [GET]

List all campground objects contained in SWEet Travels.

+ Response 200 (application/json)

        [
            {
                "description": "This 61-site campground is open all year with sites available on a first-come, first-served basis. Two sites are handicap-accessible. Flush toilets and drinking water are available late spring through early fall. Fees are half-price when water is not available. Ranger programs are offered nightly in the amphitheater during the summer. Two group campsites are reservable. Contact the park at 605.745.4600 for more information.",
                "directionsInfo": "The Elk Mountain Campground is located about 11 miles north of Hot Springs, or 22 miles south of Custer, off U.S. Hwy 385, about 1/2 mile west of the highway. Follow the link below for detailed directions to the visitor center; the campground entrance is approximately 1/4 mile north of the visitor center.",
                "directionsUrl": "http://www.nps.gov/wica/planyourvisit/directions.htm",
                "imageUrl": "https://media-cdn.tripadvisor.com/media/photo-s/04/23/63/8b/elk-mountain-campground.jpg",
                "internetInfo": "",
                "model": "campground",
                "name": "Elk Mountain Campground",
                "parkCode": "wica",
                "parkName": "Wind Cave National Park",
                "regulations": "",
                "regulationsUrl": "None",
                "searchString": "",
                "states": "SD",
                "totalSites": 61,
                "weatherInfo": "Spring:  Highs range from 50 - 70 F with highly variable weather. Spring is the park's wettest season.\n\nSummer:  Warm and generally dry with highs in the 80s F. Thunderstorms capable of producing large hail and severe lightning are common. \n\nFall:  Generally dry with warm days and cool nights. Highs in the 50s - 60s F. Lows below freezing are common.\n\nWinter: Highs in the upper 30s F with lows in the 10s F. Snowfall averages 30 inches annually, periodically closing park roads.",
                "wheelchairAccess": ""
            },
            {
                "description": "Located on Isle au Haut, a rugged island off the coast of Stonington, this remote and inaccessible to automobiles campground is linked to the mainland by mailboat. Five primitive sites are available from May 15 to October 15 by advance reservation.",
                "directionsInfo": "Duck Harbor Campground is located on Isle au Haut, a rugged island off the coast of Stonington, Maine. Remote and inaccessible to automobiles, Isle au Haut is linked to the mainland by mailboat.",
                "directionsUrl": "http://www.nps.gov/acad/planyourvisit/duckharbor.htm",
                "imageUrl": "https://cdn.acadianationalpark.com/images/content/19955_hPWIB_Duck_Harbor_Campground_lg.jpg",
                "internetInfo": "",
                "model": "campground",
                "name": "Duck Harbor Campground",
                "parkCode": "acad",
                "parkName": "Acadia National Park",
                "regulations": "Five primitive sites are available at Duck Harbor from May 15 to October 15 by advance reservation. You must have a reservation to camp. Camping is permitted in designated sites only, and party size is limited to six persons per site. Facilities include:\n\nFive lean-to shelters, three-sided with roof and floor. Dimensions are 8' tall, 8' deep, and 12.5' wide. Use of tents is limited to what can fit inside the shelters.\nFire ring\nPicnic table\nComposting toilet\nHand pump for water located 1,600 feet from shelters.\nCheckout: 11 a.m.\nQuiet hours are from 10 p.m. to 8 a.m. Generator use is prohibited.",
                "regulationsUrl": "http://www.nps.gov/acad/learn/management/lawsandpolicies.htm",
                "searchString": "",
                "states": "ME",
                "totalSites": 5,
                "weatherInfo": "Summer temperatures range from 45-90F (7-30C). Fall temperatures range from 30-70F (-1-21C). Spring temperatures range from 30-70F (-1-21C).",
                "wheelchairAccess": ""
            }, 
            {
                ...
            }
        ]