runtime: python27
api_version: 1
threadsafe: true
service: default

env_variables:
    CLOUDSQL_CONNECTION_NAME: sweet-travels:us-central1:myinstance
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: swetravels

libraries:
- name: MySQLdb
  version: "latest"
- name: webapp2
  version: "latest"

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
# [END handlers]
